### ISSUE TITLE
Error on routes branch: "No configuration found in configurations directory...Configuration property 'db:url' not defined"

### ISSUE THREAD

**Issue by akaplo** [akaplo/falconproj#12]
<img width="1046" alt="screen shot 2015-11-20 at 2 20 56 pm" src="https://cloud.githubusercontent.com/assets/7144148/11309449/f12398a4-8f91-11e5-9809-85a712667565.png">

**Comment by Bendanzigumass** [comment]
You need to create a "config" directory on your own for this to work. Andrew sent us all an email on how to get this set up

**Comment by akaplo** [comment]
Got it. created config directory, touched file named "default.json" and copied the code from Andrew's email.
