### ISSUE TITLE
BAREBONES Session Support Needed

### ISSUE THREAD

**Issue by akaplo** [akaplo/falconproj#4]
Part of our project is adding session support.  This should be fairly straightforward, as we can use most of the code from IPA03, which leverages Express middleware to do basically the same thing.  He/she who accepts this has a very important task, as the rest of our app rides on this support.

**Comment by akaplo** [comment]
Any progress on this?

**Comment by Bendanzigumass** [comment]
Yes lisa and I have been implementing the session support along with the User Routes. The bulk of our work will be completed tomorrow.

**Comment by akaplo** [comment]
Sweeeet. :palm_tree:

**Comment by akaplo** [comment]
Closed.
