### ISSUE TITLE
Routing With Many Users

### ISSUE THREAD

**Issue by akaplo** [akaplo/falconproj#5]
The main problem we're going to face is that we must create a new route with **every user**.  This shouldn't be too hard; dynamic routing will enable us to load foundit.com/_user_id/home/_ fairly simply.

**Comment by Bendanzigumass** [comment]
Lisa and I are working on routing at the moment. We created a "routes" branch and will be making changes there.

**Comment by liudiciani** [comment]
![routes](https://cloud.githubusercontent.com/assets/10903938/11282738/e62cb2fa-8ece-11e5-972b-afb88e1eae95.jpg)

**Comment by Bendanzigumass** [comment]
Updated Routes (you can edit this if you look in our google drive):
![326routing](https://cloud.githubusercontent.com/assets/14946116/11284406/87edec64-8ed7-11e5-8d89-6c00fe522c5b.png)

**Comment by akaplo** [comment]
Combined with #11, closed.
