### ISSUE TITLE
Postgre and Initial Database Support

### ISSUE THREAD

**Issue by akaplo** [akaplo/falconproj#6]
The app must leverage database calls via our PostgreSQL handler.  This issue covers barebones Postgre support.
1. Including it in app.js
2. Ensuring that the proper connections are made
3. Initializing the table(s)
   1. User table
4. Storing the tables and database info
   - This will be in the form of a .sql file
   - This file should only need to be created once
   - This file should be shared with all team members for testing
     - Sharing via Github is fine, but recommend creating _FAKE_ info.

**Comment by araleigh** [comment]
config howto: https://www.npmjs.com/package/config 

sql ref: http://umass-cs-326.github.io/weeks/09/09-relational.html

**Comment by araleigh** [comment]
Current look at db Schema:

 uid | fname  |  lname  |       email        | password | uurl  | admin |     phone      
-----+--------+---------+--------------------+----------+-------+-------+----------------
   1 | Andrew | Raleigh | araleigh@umass.edu | *******   | 1x2y3 | yes   | (908)-670-9159
   2 | John   | Doe     | jdoe@umass.edu     | *******  | 56qp2 | no    | (415)-222-2222
(2 rows)

**Comment by akaplo** [comment]
Closed by #9.
