### ISSUE TITLE
Git and Github Tutorials

### ISSUE THREAD

**Issue by akaplo** [akaplo/falconproj#8]
Create a file/tutorial with the commands that we'll all use to make the repository do what we need it to do.
1. Branch
   - add
   - delete
2. Fork?

**Comment by araleigh** [comment]
https://www.youtube.com/watch?v=oFYyTZwMyAg

**Comment by akaplo** [comment]
Also [repository wiki page.](https://github.com/akaplo/falconproj/wiki/Git-Commands)

The links in these two comments should close this issue.
